### ISSUE TITLE
זמן המשחק

### ISSUE THREAD

**Issue by HadarBitan** [our-game-maya-and-michael/Bonk-Bolt#11]
לטעמי כמות הזמן למשחק היא מעטה אני שיחקתי במשך כמה דקות ולא הצלחתי לתפוס את האחרון, מאוד קשה לעבור את השלב לדעתי.

**Comment by MayaHadad** [comment]
הוספנו כמה שניות לשלב הראשון כדי לאפשר ליותר שחקנים להצליח אותו בפעמים הראשונות.
