### ISSUE TITLE
עיצוב שלב 2

### ISSUE THREAD

**Issue by EdenRoas** [our-game-maya-and-michael/Bonk-Bolt#12]
הייתי משנה את העיצוב משלב 1 לשלב 2 כי לרגע לא שמתי לב שהתקדמתי שלב וגם כדי להוסיף עניין חדש.

**Comment by MayaHadad** [comment]
הוספנו מסך שבו לוחצים לשלב הבא כדי שיהיה ברור שהשחקן נכנס לשלב חדש. 
בנוסף, העיצוב של הפלטפורמה הראשונה זהה אך יש פלטפורמה נוספת בעיצוב אחר.
כמו כן, כתוב גם בצד ימין למעלה של המסך באיזה שלב השחקן.
