### ISSUE TITLE
ספאם ללחיצת התפיסה

### ISSUE THREAD

**Issue by Dorshir** [our-game-maya-and-michael/Bonk-Bolt#13]
שחקן יכול להספים את הלחיצה של התפיסה, אם זו כוונת המשורר, האנימציה לא נעימה אם השחקן מספים את הלחיצה, ואם זו לא כוונת המשורר, אז כדאי לשים קצת דיליי בין ניסיון תפיסה

**Comment by Dorshir** [comment]
שמתי לב שעניתם על זה חלקית, אבל זה לא מרגיש מושלם, לא ברורה ההגבלה

**Comment by Michael-Aga** [comment]
זאת לא הכוונה והוספנו על זה דיליי תודה על הפידבק.
