### ISSUE TITLE
שעון הזמן שנגמר

### ISSUE THREAD

**Issue by liron02319** [our-game-maya-and-michael/Bonk-Bolt#14]
משחק נורא נחמד ! הבעיה כשאתה מרוכז במשחק במטרה לתפוס אז כשהזמן נגמר ישר הוא עושה RESTART בלי להודיע לשחקן בכלל, 
פיתרון-להוסיף חלון או משהו קטן שיודיע לשחקן

**Comment by MayaHadad** [comment]
הוספנו חלון עם כפתור לשלב הבא
