### ISSUE TITLE
 לא ברור את מי לתפוס ואיך

### ISSUE THREAD

**Issue by AdiNahmias** [our-game-maya-and-michael/Bonk-Bolt#15]
במשחק הראשון לא היו לי חיצים מעל מי שהייתי צריכה לתפוס. עד שמצליחים להתמצא במשחק הזמן נגמר..

**Comment by MayaHadad** [comment]
יש שלב ניסיון, כנראה שלא שיחקת אותו כי שם יש הסבר למקשים ואת מי צריך לתפוס
