### ISSUE TITLE
תפיסה

### ISSUE THREAD

**Issue by EliGreenblatt** [our-game-maya-and-michael/Bonk-Bolt#16]
משחק מאוד יפה ומושך את העין, התמונה ברקע מרגיש לי קצת לא תואם את האומנות אבל בתפיסה אולי אפשר משהו יותר וויזואלי שתפסתי שיהיה איזה פיצוץ קטן או משהו, ודרך אגב אני אוהב את זה שהאנשים נעלמים

**Comment by Michael-Aga** [comment]
גם אנחנו אהבנו, וטיפלנו בבעיה שנתפס הוספנו אפקט של מכה, תודה על הפידבק.
