### ISSUE TITLE
תפיסה והליכה של השחקנים

### ISSUE THREAD

**Issue by MatanAdar** [our-game-maya-and-michael/Bonk-Bolt#18]
המשחק נראה טוב אבל לפעמים התפיסה לא עובדת למרות שאני ליד השחקן וגם ההליכה של האנשים שצריך לתפוס לפעמים לא הגיונית(עפים אחורה).

**Comment by Michael-Aga** [comment]
תודה על הפידבק טיפלנו בזה.
