### ISSUE TITLE
השחקנים לא הולכים כמו שצריך

### ISSUE THREAD

**Issue by itamarc101** [our-game-maya-and-michael/Bonk-Bolt#3]
כשהדמויות הולכות - הן נתקעות בקיר והולכות במקום
לפעמים דמות הולכת במקום ומשתגרת רחוק פתאום
מצרף סרטון

https://github.com/our-game-maya-and-michael/Bonk-Bolt/assets/45041126/30c583c0-29cc-4ca7-873b-2e2ce1ae4cc1

**Comment by MayaHadad** [comment]
באיזה שלב זה קרה לך? 
ראינו שהייתה בעיה בשלב הניסיון וזה תוקן

**Comment by MayaHadad** [comment]
תוקן. 
הוספנו מצב שאם השחקנים לא הגיעו ליעד הרנדומלי תוך 2 שניות, הם יקבלו יעד חדש וכך הם לא יתקעו.
