### ISSUE TITLE
יש מקום שאפשר לעמוד בו באוויר מחוץ לתחום הנכון 

### ISSUE THREAD

**Issue by Maor-Or** [our-game-maya-and-michael/Bonk-Bolt#4]
בשלב 3 יש מקום שאפשר לעמוד בו במקום ליפול ולהיפסל, בנוסף הפלטפורמות מעבר קשות לקפיצה עליהן
![WhatsApp Image 2024-03-06 at 00 41 43](https://github.com/our-game-maya-and-michael/Bonk-Bolt/assets/118377261/5cc6c12d-388e-453e-a5b0-c3c3f7ed9b66)

**Comment by Michael-Aga** [comment]
תודה רבה על המשוב, טיפלנו בזה.
