### ISSUE TITLE
 שלב 2 קשה מדי+ הליכה מוזרה +תפיסה מוזרה 

### ISSUE THREAD

**Issue by ohadtaizi** [our-game-maya-and-michael/Bonk-Bolt#7]
שלב 2 קשה מדי
לא יודע אם זה הכוונה של המפתחים אבל השחקן נראה הרבה פעמים מחליק ולא הולך , אם הוא נתקע במשהו לוקח לו זמן לשנות כיוון .
לפעמים לא תופסים למרות שזה נראה שתופסים .

**Comment by Michael-Aga** [comment]
טיפלנו בבעיה, תודה על המשוב.
