### ISSUE TITLE
התפיסה

### ISSUE THREAD

**Issue by hodwys** [our-game-maya-and-michael/Bonk-Bolt#8]
לא ככ ברור איך תוספים את השחקנים ניסיתי להגיע אליהם ולקפוץ וזה לא עבד לי ולא הבנתי למה.

**Comment by MayaHadad** [comment]
יש הסבר בשלב הניסיון מה כל מקש עושה. בין היתר יש שם תמונה של לחצן שמאלי לתפיסת השחנים.
